export const iconOptions = [
    {
        subcategory: 'office',
        iconFamily: 'Entypo',
        iconName: 'archive',
        tags: ['archive','drawer','file'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-right-bold',
        tags: ['forward'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-up-bold',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-down-bold',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-left-bold',
        tags: ['reply','back'],
    },
    {
        subcategory: 'food',
        iconFamily: 'Entypo',
        iconName: 'bowl',
        tags: ['ramen','bowl','dinner'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'brush',
        tags: ['paint','brush'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'briefcase',
        tags: ['briefcase','business','trip','bag'],
    },
    {
        subcategory: 'household',
        iconFamily: 'Entypo',
        iconName: 'bucket',
        tags: ['bucket','mop'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Entypo',
        iconName: 'bug',
        tags: ['bug','insect'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cake-variant',
        tags: ['cake','birthday','dessert'],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'calendar',
        tags: ['calendar','appointment','date','schedule','meeting'],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'calendar-clock',
        tags: ['appointment','calendar','schedule','date','meeting'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'camera',
        tags: ['camera','photo','picture','snap'],
    },
    {
        subcategory: 'people',
        iconFamily: 'Entypo',
        iconName: 'chat',
        tags: ['talk','conversation','ask','chat','discuss'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'code',
        tags: ['code','program'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Entypo',
        iconName: 'controller-record',
        tags: ['round','circle','ball'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Entypo',
        iconName: 'controller-stop',
        tags: ['square','box'],
    },
    {
        subcategory: 'food',
        iconFamily: 'Entypo',
        iconName: 'cup',
        tags: ['drink','cup'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'database',
        tags: ['database','server'],
    },
    {
        subcategory: 'people',
        iconFamily: 'Entypo',
        iconName: 'eye',
        tags: ['eye','look'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Entypo',
        iconName: 'flashlight',
        tags: ['flashlight','search','light'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Entypo',
        iconName: 'help',
        tags: ['ask','question','help'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'keyboard',
        tags: ['keyboard','type','write'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Entypo',
        iconName: 'lab-flask',
        tags: ['flask'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'laptop',
        tags: ['computer','laptop','internet','program','code'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'list-ul',
        tags: ['list','checklist','note','idea'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'list-ol',
        tags: ['list','checklist','step','instructions','order'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'mic',
        tags: ['record','mic'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'mobile-alt',
        tags: ['phone','call','device','mobile'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'mouse-pointer',
        tags: ['mouse','pointer','computer','internet'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialIcons',
        iconName: 'new-releases',
        tags: ['important','new','careful','urgent'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cart',
        tags: ['buy','order','cart','shop'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shuffle-variant',
        tags: ['shuffle','cross','random','switch','swap'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'sound-mix',
        tags: ['adjust','tune','control','mix'],
    },
    {
        subcategory: 'time',
        iconFamily: 'FontAwesome5',
        iconName: 'stopwatch',
        tags: ['stopwatch','time','clock','measure'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'Entypo',
        iconName: 'suitcase',
        tags: ['suitcase','baggage','trip','travel','pack'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'tablet-alt',
        tags: ['tablet','device'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'ticket-alt',
        tags: ['ticket','event','admission','concert','cinema','theatre'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'traffic-cone',
        tags: ['construction','cone'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'trending-down',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'trending-up',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'weather-windy',
        tags: ['wind','blow','air','puff'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'glass-martini-alt',
        tags: ['martini','cocktail','drink'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'search',
        tags: ['look','find','search','inspect'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cards-heart',
        tags: ['love','date','girlfiend','boyfriend','husband','wife','heart','happy','like'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'check',
        tags: ['check','finish','complete'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'times',
        tags: ['remove','delete','stop','cancel'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'cog',
        tags: ['gear','cog','settings','gadget','tinker'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'cogs',
        tags: ['gear','cog','settings','gadget','tinker'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'compress-arrows-alt',
        tags: [['gather','arrows','compress']],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'expand-arrows-alt',
        tags: [['arrows','expand']],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'arrows-alt',
        tags: [['move','direction','arrows','position']],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'asterisk',
        tags: ['asterisk'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'leaf',
        tags: ['leaf','plant'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'sign-out-alt',
        tags: ['take out','remove'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'sign-in-alt',
        tags: ['put in','install','go in'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'thumbtack',
        tags: ['pin','schedule'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'bullhorn',
        tags: ['megaphone','bullhorn','announce','shout'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'link',
        tags: ['chain','link','connect'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'money-bill-alt',
        tags: ['pay','buy','order','money','dollar'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialIcons',
        iconName: 'mail',
        tags: ['envelope','letter','mail'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'medical-bag',
        tags: ['medkit','medical','first aid','medicine','treat'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'quote-left',
        tags: ['quote','word','text'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'quote-right',
        tags: ['quote','word','text'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'anchor',
        tags: ['anchor','stop','stay','hold'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'compass',
        tags: ['compass','direction'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'dollar-sign',
        tags: ['dollar','price','cost','buy','money'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'euro-sign',
        tags: ['euro'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'pound-sign',
        tags: ['pound'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'university',
        tags: ['bank','university'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'utensil-spoon',
        tags: ['eat','spoon'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'paw',
        tags: ['paw','animal','pet'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'recycle',
        tags: ['recycle','conserve','environment'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'tree',
        tags: ['tree','nature','outside','plant'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'soccer',
        tags: ['soccer','football','futbol'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'binoculars',
        tags: ['binoculars','scope','search','spot'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'motorcycle',
        tags: ['motocycle','bike'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'venus',
        tags: ['venus','woman','women','female','girl'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'mars',
        tags: ['mars','man','men','male','boy'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'bed',
        tags: ['bed','sleep','night','tired'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'subway',
        tags: ['subway'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'note',
        tags: ['note','memo','message','comment','text','letter'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'percent',
        tags: ['percent'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'handshake',
        tags: ['handshake','meeting','deal','contract','agree','contract'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'thermometer-half',
        tags: ['thermometer','weather','temperature','hot','cold','warm','cool'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'snowflake',
        tags: ['snow','winter','cold','freeze'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'atom',
        tags: ['atom'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'award',
        tags: ['award','win'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'baby',
        tags: ['baby','toddler','kid'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'baby-carriage',
        tags: ['carriage','baby','toddler','kid'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'balance-scale',
        tags: ['scale','balance','justice','compare','consider','weigh'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'band-aid',
        tags: ['band-aid','bandaid','first aid','cut','injury','bleed','blood','hurt','bandage'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'basketball-ball',
        tags: ['backetball','ball'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'beer',
        tags: ['beer','brew','pint','bar','alcohol','drink'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'bicycle',
        tags: ['bicycle','bike','cycle'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'biking',
        tags: ['biking','bike ride','cycling','biking'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'biohazard',
        tags: ['biohazard','danger','caution'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'black-tie',
        tags: ['suit','tie','formal','fancy'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'bolt',
        tags: ['power','electric','bolt','shock','lightning'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bone',
        tags: ['bone','skeleton'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'book-open',
        tags: ['book','read'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'bowling-ball',
        tags: ['bowling'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'box-open',
        tags: ['box','cardboard','pack','unpack'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'brain',
        tags: ['brain','think','mind','idea'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'brush',
        tags: ['paint','brush'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'bus',
        tags: ['bus'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'campground',
        tags: ['camp','tent'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'cannabis',
        tags: ['weed','cannabis'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'capsules',
        tags: ['vitamin','prescription','medication','capsules','pills','drugs'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'car',
        tags: ['car','drive','roadtrip'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'car-battery',
        tags: ['battery'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'car-side',
        tags: ['car','drive','roadtrip'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'caravan',
        tags: ['camper','caravan','trailer'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'carrot',
        tags: ['carrot','vegetable','veggie'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'cat',
        tags: ['cat','kitty','meow','kitten'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'chair',
        tags: ['chair','sit'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'chart-pie',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'chart-bar',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'cheese',
        tags: ['cheese'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'chess',
        tags: ['chess'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'child',
        tags: ['kid'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'church',
        tags: ['church'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'city',
        tags: ['building','city'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'clipboard-list',
        tags: ['list','inventory','checklist','record','log'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'cloud',
        tags: ['cloud'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'code-branch',
        tags: ['code','branch'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'coins',
        tags: ['change','coins','quarters'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'cookie-bite',
        tags: ['cookie','snack','dessert','treat'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'couch',
        tags: ['couch','relax','break','rest'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'cross',
        tags: ['cross'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'crow',
        tags: ['crow'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'crown',
        tags: ['crown'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'cut',
        tags: ['scissors','cut','trim','slice'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'dice',
        tags: ['random','dice','roll','game'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'dice-d20',
        tags: ['random','dice','roll','d20','dnd','game','role play'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'dove',
        tags: ['bird'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'dragon',
        tags: ['dragon','fantasy','dnd'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'drum',
        tags: ['drum','music','beat'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'dumpster',
        tags: ['garbage','rubbish','bin','trash','dumpster'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'egg',
        tags: ['egg','breakfast'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'dog',
        tags: ['dog','woof','bark','puppy'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'faucet',
        tags: ['faucet','water','spigot','spout'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'feather-alt',
        tags: ['feather','bird'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'female',
        tags: ['woman','female','girl'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'fish',
        tags: ['fish'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'football-ball',
        tags: ['football','ball','superbowl'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'frog',
        tags: ['frog'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'gas-pump',
        tags: ['gas','feul','petrol'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'gavel',
        tags: ['judge','gavel'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'gamepad',
        tags: ['controller','game','video game'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'ghost',
        tags: ['ghost','scary','horror','paranormal'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'gift',
        tags: ['present','gift','birthday','christmas'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'glasses',
        tags: ['glasses','vision','optometrist','lense'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'globe',
        tags: ['world','globe','earth'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'earth',
        tags: ['earth','world','planet'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'guitar',
        tags: ['guitar','music','song'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'hamburger',
        tags: ['burger','lunch'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'hammer',
        tags: ['hammer','build','fix','nail'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'hard-hat',
        tags: ['hard-hat','hardhat','construction'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'hat-cowboy',
        tags: ['cowboy','west','country','wrangle'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'hat-wizard',
        tags: ['wizard','mage','magic','dnd','role play'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'headphones',
        tags: ['headphones','music','listen','audio'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'helicopter',
        tags: ['helicopter'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'hiking',
        tags: ['hiking','hike','trek','climb'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'horse',
        tags: ['horse'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'hospital-alt',
        tags: ['hospital','emergency'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'hotdog',
        tags: ['hotdog','lunch'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'icicles',
        tags: ['icicle','frozen','winter','cold','freeze','freezing'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'infinity',
        tags: ['infinite','infinity','eternity','forever','unlimited'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'key',
        tags: ['key','password','access','entry'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'lemon',
        tags: ['lemon','lime'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'lightbulb',
        tags: ['idea','think','thought','lightbulb','light','concept','brainstorm'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'lock',
        tags: ['lock','secure','protect','close'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'magic',
        tags: ['magic','wand'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'male',
        tags: ['man','male','boy'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'marker',
        tags: ['marker'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'mask',
        tags: ['mask'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'medal',
        tags: ['medal'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'microchip',
        tags: ['microchip','processor','ram'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'mitten',
        tags: ['mitten','cold','winter'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'mosque',
        tags: ['mosque'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'mouse',
        tags: ['mouse'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'mug-hot',
        tags: ['coffee','mug','tea','cup','brew'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'music',
        tags: ['music','note','song','sound'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'oil-can',
        tags: ['oil','lub'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'paint-roller',
        tags: ['paint','roller'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'palette',
        tags: ['palette'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'peace',
        tags: ['peace'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'pen-alt',
        tags: ['pen','write','draw'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'pencil-alt',
        tags: ['pencil','write','draw','sketch'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'people-carry',
        tags: ['carry','deliver','move'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'pepper-hot',
        tags: ['pepper','spice','spicy'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'phone-alt',
        tags: ['call','phone'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'pizza-slice',
        tags: ['pizza','slice'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'plane-arrival',
        tags: ['arrive','arrival','flight','plane'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'plane-departure',
        tags: ['departure','depart','flight','plane'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'place-of-worship',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'plug',
        tags: ['plug','power','hook'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'poop',
        tags: ['poo','shit','bathroom','turd'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'pray',
        tags: ['pray'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'prescription-bottle',
        tags: ['prescription','medication','vitamin'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'puzzle-piece',
        tags: ['puzzle','jigsaw'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'rainbow',
        tags: ['rainbow','arch'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'radiation',
        tags: ['radiation'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'redo',
        tags: ['turn','refresh','clockwise'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'undo',
        tags: ['turn','counter-clockwise','counter clockwise'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'ring',
        tags: ['ring'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'road',
        tags: ['road','trip','drive','travel','street','highway'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'robot',
        tags: ['robot','ai','computer'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'rocket',
        tags: ['rocket'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'ruler',
        tags: ['measure','ruler'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'running',
        tags: ['run','jog','sprint','exercise','workout'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'screwdriver',
        tags: ['screwdriver','fix','tighten'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'seedling',
        tags: ['plant','sprout','leaf'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shape',
        tags: ['shapes'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'shuttle-van',
        tags: ['shuttle','van'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'shower',
        tags: ['shower'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'skating',
        tags: ['skate','skating'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'skiing',
        tags: ['ski'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'skull',
        tags: ['skull'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'smoking',
        tags: ['smoke','smoking'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'snowman',
        tags: ['snowman','winter'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'spider',
        tags: ['spider'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'store-alt',
        tags: ['store','shop'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'syringe',
        tags: ['shot','syringe','vaccine','injection'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'sync-alt',
        tags: ['sync','refresh'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'table-tennis',
        tags: ['ping pong','table tennis'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'tag',
        tags: ['tag','label'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'taxi',
        tags: ['taxi','cab','uber'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'toilet',
        tags: ['toilet','bathroom','restroom'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'toolbox',
        tags: ['toolbox','toolkit'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'tractor',
        tags: ['tractor'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'truck-pickup',
        tags: ['truck','pickup'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'truck',
        tags: ['truck'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'trophy',
        tags: ['trophy','prize','win'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'tshirt',
        tags: ['shirt','dressed','clothes','clothing'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'tv',
        tags: ['tv','television','watch'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'umbrella-beach',
        tags: ['beach','parasol'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'unlock',
        tags: ['unlock','open'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'user-friends',
        tags: ['friend','meet'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'utensils',
        tags: ['meal','eat','silverware'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'vial',
        tags: ['vial'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'walking',
        tags: ['walk'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'warehouse',
        tags: ['garage'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'wheelchair',
        tags: ['wheelchair'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'wine-bottle',
        tags: ['wine'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'wine-glass',
        tags: ['wine'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'yin-yang',
        tags: ['yin','yang'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'umbrella',
        tags: ['umbrella'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'magnet',
        tags: ['magnet'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'flask',
        tags: ['flask','experiment'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'ban',
        tags: ['stop',`don't`,'cancel','remove','throw away'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'power-off',
        tags: ['power'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'map-outline',
        tags: ['map','directions','plan'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'shopping-basket',
        tags: ['grocery','shop'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'star',
        tags: ['star','favorite'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'yen-sign',
        tags: ['yen'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Ionicons',
        iconName: 'logo-bitcoin',
        tags: ['bitcoin'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'Ionicons',
        iconName: 'barbell',
        tags: ['weight','gym','workout','exercise'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Ionicons',
        iconName: 'build',
        tags: ['wrench','fix','tighten'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Ionicons',
        iconName: 'card-outline',
        tags: ['buy','order','credit','shop','purchase'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Ionicons',
        iconName: 'construct',
        tags: ['tools','build','fix','assemble','put together'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'cube',
        tags: ['box','cube'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'Ionicons',
        iconName: 'golf',
        tags: ['golf'],
    },
    {
        subcategory: 'people',
        iconFamily: 'Ionicons',
        iconName: 'hand-left',
        tags: ['left','hand'],
    },
    {
        subcategory: 'people',
        iconFamily: 'Ionicons',
        iconName: 'hand-right',
        tags: ['right','hand'],
    },
    {
        subcategory: 'places',
        iconFamily: 'Ionicons',
        iconName: 'home',
        tags: ['house','home'],
    },
    {
        subcategory: 'food',
        iconFamily: 'Ionicons',
        iconName: 'ice-cream',
        tags: ['ice cream','dessert','treat'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'layers',
        tags: ['layer','stack'],
    },
    {
        subcategory: 'household',
        iconFamily: 'Ionicons',
        iconName: 'library-sharp',
        tags: ['book','library','read'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'moon',
        tags: ['moon'],
    },
    {
        subcategory: 'time',
        iconFamily: 'Ionicons',
        iconName: 'notifications',
        tags: ['alarm','notification','bell'],
    },
    {
        subcategory: 'office',
        iconFamily: 'Ionicons',
        iconName: 'newspaper',
        tags: ['news'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'planet',
        tags: ['planet','space'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Ionicons',
        iconName: 'print',
        tags: ['print','copy','fax'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'rainy',
        tags: ['rain','storm','weather'],
    },
    {
        subcategory: 'office',
        iconFamily: 'Ionicons',
        iconName: 'reader',
        tags: ['book','document','write'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'Ionicons',
        iconName: 'school',
        tags: ['graduat','school'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'shield',
        tags: ['shield','protect','defend'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'sunny',
        tags: ['sun','weather','warm'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'Ionicons',
        iconName: 'tennisball',
        tags: ['tennis','baseball'],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialIcons',
        iconName: 'access-time',
        tags: ['time','schedule','appointment','agenda','clock'],
    },
    {
        subcategory: 'household',
        iconFamily: 'Ionicons',
        iconName: 'trash-sharp',
        tags: ['trash','garbage','bin'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Ionicons',
        iconName: 'wallet-sharp',
        tags: ['wallet','cash','money'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'warning-sharp',
        tags: ['alert','important','urgent'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'water',
        tags: ['water','drop'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'Ionicons',
        iconName: 'ios-airplane',
        tags: ['flight','plane'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'flag',
        tags: ['flag'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Ionicons',
        iconName: 'calculator',
        tags: ['calculat','math','add','estimate','figure'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'alien',
        tags: ['alien'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'ambulance',
        tags: ['ambulance','emergency'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arm-flex',
        tags: ['strong','workout','exercise','weights','gym'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'axe',
        tags: ['axe','chop'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'axe-battle',
        tags: ['axe'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'baguette',
        tags: ['bread','baguette'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'balloon',
        tags: ['balloon'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bat',
        tags: ['bat'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'battery-high',
        tags: ['battery'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'billiards',
        tags: ['pool'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bird',
        tags: ['bird'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'blender',
        tags: ['blender','smoothie'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bomb',
        tags: ['bomb'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'book',
        tags: ['book','read','library'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bow-arrow',
        tags: ['bow','arrow','archery'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'box-cutter',
        tags: ['box cutter','open','knife'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'boxing-glove',
        tags: ['boxing','fight'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'broom',
        tags: ['broom','sweep','clean'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'butterfly',
        tags: ['butterfly'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cactus',
        tags: ['cactus'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'candy',
        tags: ['candy','treat','dessert'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'card-text',
        tags: ['card','note','text'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cards',
        tags: ['cards'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cat',
        tags: ['cat','kitty','mewo','kitten'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'dog',
        tags: ['dog','woof','bark','puppy'],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'chat',
        tags: ['talk','speech','lecture','say'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'checkerboard',
        tags: ['chess','checkers'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'chef-hat',
        tags: ['chef','cook'],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'comment-text',
        tags: ['talk','speech','lecture','say'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cow',
        tags: ['cow'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'earbuds',
        tags: ['earbuds','listen','music'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'eraser',
        tags: ['eras'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'file',
        tags: ['file','page','document'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'folder',
        tags: ['folder','categor'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        tags: ['flower'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'food-apple',
        tags: ['apple','fruit'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'food-drumstick',
        tags: ['chicken'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'french-fries',
        tags: ['fries'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'fridge',
        tags: ['fridge','meal','lunch'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'fruit-grapes',
        tags: ['grapes','berry','fruit'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'fruit-watermelon',
        tags: ['watermelon'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'hand-saw',
        tags: ['saw'],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'hand-wave',
        tags: ['wave','greet'],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'human-male-female',
        tags: ['couple','people','date'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'jellyfish',
        tags: ['jellyfish'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'karate',
        tags: ['karate','mma','martial arts'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'knife',
        tags: ['knife','chop','cut'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'knife-military',
        tags: ['knife'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'ladder',
        tags: ['ladder','climb'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'lamp',
        tags: ['lamp'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mace',
        tags: ['mace'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'magic-staff',
        tags: ['staff'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mail',
        tags: ['mail','letter','envelope','send','post'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mailbox',
        tags: ['mailbox','post','mail','send'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mirror',
        tags: ['mirror'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'nuke',
        tags: ['nuke','bomb'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'owl',
        tags: ['owl'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'panda',
        tags: ['panda'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'paper-roll-outline',
        tags: ['tp','toilet paper','paper towel'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'party-popper',
        tags: ['party','celebrate'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'piano',
        tags: ['piano'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pickaxe',
        tags: ['pickaxe'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pig-variant',
        tags: ['pig'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pliers',
        tags: ['pliers','fix'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pot-steam',
        tags: ['cook','pot'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pumpkin',
        tags: ['pumpkin'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'rabbit',
        tags: ['rabbit','fast'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'racing-helmet',
        tags: ['helmet'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'rake',
        tags: ['rake'],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'reminder',
        tags: ['remind','remember'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'remote',
        tags: ['remote','control'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'rice',
        tags: ['bowl','rice'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'roller-skate',
        tags: ['skating','roller','skate'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sack',
        tags: ['bag'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sail-boat',
        tags: ['sail'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sd',
        tags: ['sd card','save'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'seat',
        tags: ['chair','sit'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'seed',
        tags: ['seed','plant'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shoe-sneaker',
        tags: ['shoe'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shoe-formal',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shoe-heel',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shopping',
        tags: ['shopping','grocery'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shimmer',
        tags: ['new'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'ship-wheel',
        tags: ['navigat'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shovel',
        tags: ['shovel','dig'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'skateboarding',
        tags: ['skateboard'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'snail',
        tags: ['snail','slow'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'snake',
        tags: ['snake'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'space-invaders',
        tags: ['alien','arcade'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'spray-bottle',
        tags: ['clean','spray'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sword',
        tags: ['sword'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'table-furniture',
        tags: ['dinner','lunch','table'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'teddy-bear',
        tags: ['teddy','bear'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'telescope',
        tags: ['telescope'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'television-classic',
        tags: ['tv','television','watch'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'terrain',
        tags: ['mountain'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'tortoise',
        tags: ['turtle','tortoise','fast'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'usb-flash-drive',
        tags: ['flash','save'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'vacuum',
        tags: ['vacuum'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'virus',
        tags: ['virus'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'wall',
        tags: ['wall','brick'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'yoga',
        tags: ['yoga'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialIcons',
        iconName: '360',
        tags: ['turn','360'],
    },
    {
        subcategory: 'places',
        iconFamily: 'MaterialIcons',
        iconName: 'apartment',
        tags: ['building','apartment','complex'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialIcons',
        iconName: 'attachment',
        tags: ['attach','paperclip'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialIcons',
        iconName: 'bathtub',
        tags: ['bath'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-boat',
        tags: ['boat'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-car',
        tags: ['car','drive'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-bus',
        tags: ['bus'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-bike',
        tags: ['bike','bicycle'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-walk',
        tags: ['walk'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-run',
        tags: ['run'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'elderly',
        tags: ['cane','elderly'],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialIcons',
        iconName: 'fingerprint',
        tags: ['fingerprint'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialIcons',
        iconName: 'local-fire-department',
        tags: ['fire','burn','cook','hot','flame'],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialIcons',
        iconName: 'microwave',
        tags: ['microwave'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialIcons',
        iconName: 'pest-control-rodent',
        tags: ['mouse','rat','rodent'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialIcons',
        iconName: 'plumbing',
        tags: ['wrench','plumbing','pipes','fix','leak'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'pool',
        tags: ['swim','pool'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'door-closed',
        tags: ['door'],
    },
];
