export const iconOptions = [
    {
        subcategory: 'office',
        iconFamily: 'Entypo',
        iconName: 'archive',
        tags: ['archive','drawer','file'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-right-bold',
        tags: ['right','arrow'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-up-bold',
        tags: ['up','arrow'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-down-bold',
        tags: ['down','arrow'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arrow-left-bold',
        tags: ['left','arrow'],
    },
    {
        subcategory: 'food',
        iconFamily: 'Entypo',
        iconName: 'bowl',
        tags: ['ramen','bowl','dinner'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'brush',
        tags: ['paint','brush'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'briefcase',
        tags: ['briefcase','business','trip','bag'],
    },
    {
        subcategory: 'household',
        iconFamily: 'Entypo',
        iconName: 'bucket',
        tags: ['bucket','mop'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Entypo',
        iconName: 'bug',
        tags: ['bug','insect'],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cake-variant',
        tags: ['cake','birthday','dessert'],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'calendar',
        tags: ['calendar','appointment','date','schedule','meeting'],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'calendar-clock',
        tags: ['appointment','calendar','schedule','date','meeting'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'camera',
        tags: ['camera','photo','picture','snap'],
    },
    {
        subcategory: 'people',
        iconFamily: 'Entypo',
        iconName: 'chat',
        tags: ['talk','conversation','ask','chat','discuss'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'code',
        tags: ['code','program'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Entypo',
        iconName: 'controller-record',
        tags: ['round','circle','ball'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Entypo',
        iconName: 'controller-stop',
        tags: ['square','box'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Entypo',
        iconName: 'credit-card',
        tags: ['buy','order','credit','shop','purchase'],
    },
    {
        subcategory: 'food',
        iconFamily: 'Entypo',
        iconName: 'cup',
        tags: ['drink','cup'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'database',
        tags: ['database','server'],
    },
    {
        subcategory: 'people',
        iconFamily: 'Entypo',
        iconName: 'eye',
        tags: ['eye','look'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Entypo',
        iconName: 'flashlight',
        tags: ['flashlight','search','light'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Entypo',
        iconName: 'help',
        tags: ['ask','question','help'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'keyboard',
        tags: ['keyboard','type','write'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Entypo',
        iconName: 'lab-flask',
        tags: ['flask'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'laptop',
        tags: ['computer','laptop','internet','program','code'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'list-ul',
        tags: ['list','checklist','note','idea'],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'list-ol',
        tags: ['list','checklist','step','instructions','order'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'mic',
        tags: ['record','mic'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'mobile-alt',
        tags: ['phone','call','device','mobile'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'mouse-pointer',
        tags: ['mouse','pointer','computer','internet'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialIcons',
        iconName: 'new-releases',
        tags: ['important','new','careful','urgent'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cart',
        tags: ['buy','order','cart','shop'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shuffle-variant',
        tags: ['shuffle','cross','random','switch','swap'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Entypo',
        iconName: 'sound-mix',
        tags: ['adjust','tune','control','mix'],
    },
    {
        subcategory: 'time',
        iconFamily: 'FontAwesome5',
        iconName: 'stopwatch',
        tags: ['stopwatch','time','clock','measure'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'Entypo',
        iconName: 'suitcase',
        tags: ['suitcase','baggage','trip','travel','pack'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'tablet-alt',
        tags: ['tablet','device'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'ticket-alt',
        tags: ['ticket','event','admission','concert','cinema','theatre'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'traffic-cone',
        tags: ['construction','cone'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'trending-down',
        tags: ['down','trend'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'trending-up',
        tags: ['up','trend'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'weather-windy',
        tags: ['wind','blow','air','puff'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'glass-martini-alt',
        tags: ['martini','cocktail','drink'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'search',
        tags: ['look','find','search','inspect'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cards-heart',
        tags: ['love','date','girlfiend','boyfriend','husband','wife','heart','happy','like'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'check',
        tags: ['check','finish','complete'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'times',
        tags: ['remove','delete','stop','cancel'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'cog',
        tags: ['gear','cog','settings','gadget','tinker'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'cogs',
        tags: ['gear','cog','settings','gadget','tinker'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'compress-arrows-alt',
        tags: [['gather','arrows','compress']],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'expand-arrows-alt',
        tags: [['arrows','expand']],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'arrows-alt',
        tags: [['move','direction','arrows','position']],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'asterisk',
        tags: ['asterisk','important','annotation'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'leaf',
        tags: ['leaf','plant'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'sign-out-alt',
        tags: ['leave','exit','out'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'sign-in-alt',
        tags: ['arrive','enter','in'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'thumbtack',
        tags: ['pin','schedule','capture'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'bullhorn',
        tags: ['megaphone','bullhorn','announce','shout'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'link',
        tags: ['chain','link','connect'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'money-bill-alt',
        tags: ['pay','buy','order','money','dollar'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialIcons',
        iconName: 'mail',
        tags: ['envelope','letter','mail'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'medical-bag',
        tags: ['medkit','medical','first aid','medicine','treat'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialIcons',
        iconName: 'reply',
        tags: ['reply','answer','back','left'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialIcons',
        iconName: 'forward',
        tags: ['forward','right','advance'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'quote-left',
        tags: ['quote','word','text'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'quote-right',
        tags: ['quote','word','text'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'anchor',
        tags: ['anchor','stop','stay','hold'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'compass',
        tags: ['compass','direction'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'dollar-sign',
        tags: ['dollar','price','cost','buy','money'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'euro-sign',
        tags: ['euro'],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'pound-sign',
        tags: ['pound'],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'university',
        tags: ['bank','university'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'utensil-spoon',
        tags: ['eat','spoon'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'paw',
        tags: ['paw','animal','pet'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'recycle',
        tags: ['recycle','conserve','environment'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'tree',
        tags: ['tree','nature','outside','plant'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'soccer',
        tags: ['soccer','football','futbol'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'binoculars',
        tags: ['binoculars','scope','search','spot'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'motorcycle',
        tags: ['motocycle','bike'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'venus',
        tags: ['venus','woman','women','female','girl'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'mars',
        tags: ['mars','man','men','male','boy'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'bed',
        tags: ['bed','sleep','night','tired'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'subway',
        tags: ['subway'],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'note',
        tags: ['note','memo','message','comment','text','letter'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'percent',
        tags: ['percent'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'handshake',
        tags: ['handshake','meeting','deal','contract','agree','contract'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'thermometer-half',
        tags: ['thermometer','weather','temperature','hot','cold','warm','cool'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'snowflake',
        tags: ['snow','winter','cold','freeze'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'atom',
        tags: ['atom'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'award',
        tags: ['award'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'baby',
        tags: ['baby','toddler','kid'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'baby-carriage',
        tags: ['carriage','baby','toddler','kid'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'balance-scale',
        tags: ['scale','balance','justice','compare','consider','weigh'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'band-aid',
        tags: ['band-aid','bandaid','first aid','cut','injury','bleed','blood','hurt','bandage'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'basketball-ball',
        tags: ['backetball','ball'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'beer',
        tags: ['beer','brew','pint','bar','alcohol','drink'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'bicycle',
        tags: ['bicycle','bike','cycle'],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'biking',
        tags: ['biking','bike ride','cycling','biking'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'biohazard',
        tags: ['biohazard','danger','caution'],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'black-tie',
        tags: ['suit','tie','formal','fancy'],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'bolt',
        tags: ['power','electric','bolt','shock','lightning'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bone',
        tags: ['bone','skeleton'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'book-open',
        tags: ['book','read'],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'bowling-ball',
        tags: ['bowling'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'box-open',
        tags: ['box','cardboard','pack','unpack'],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'brain',
        tags: ['brain','think','mind','idea'],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'brush',
        tags: ['paint','brush'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'burn',
        tags: ['fire','burn','cook','hot','flame'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'bus',
        tags: ['bus'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'campground',
        tags: ['camp','tent'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'cannabis',
        tags: ['weed','cannabis'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'capsules',
        tags: ['vitamins','perscription','capsules','pills','drugs'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'car',
        tags: ['car','drive','roadtrip'],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'car-battery',
        tags: ['battery'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'car-side',
        tags: ['car','drive','roadtrip'],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'caravan',
        tags: ['camper','caravan','trailer'],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'carrot',
        tags: ['carrot','vegetable','veggie'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'cat',
        tags: ['cat','kitty','meow','kitten'],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'chair',
        tags: ['chair','sit'],
    },
    // {
    //     subcategory: 'household',
    //     iconFamily: 'FontAwesome5',
    //     iconName: 'chair',
    //     tags: [],
    // },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'chart-pie',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'chart-bar',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'cheese',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'chess',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'child',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'church',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'city',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'clipboard-list',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'cloud',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'code-branch',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'coins',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'cookie-bite',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'couch',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'cross',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'crow',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'crown',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'cut',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'dice',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'dice-d20',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'dove',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'dragon',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'drum',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'dumpster',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'egg',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'dog',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'faucet',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'feather-alt',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'female',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'fish',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'football-ball',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'frog',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'gas-pump',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'gavel',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'gamepad',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'ghost',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'gift',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'glasses',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'globe',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'guitar',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'hamburger',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'hammer',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'hard-hat',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'hat-cowboy',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'hat-wizard',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'headphones',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'helicopter',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'hiking',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'horse',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'hospital-alt',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'hotdog',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'icicles',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'infinity',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'key',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'lemon',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'lightbulb',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'link',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'lock',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'magic',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'male',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'marker',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'mask',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'medal',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'microchip',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'mitten',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'mosque',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'mouse',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'mug-hot',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'music',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'oil-can',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'paint-roller',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'paint-brush',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'palette',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'peace',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'pen-alt',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'pencil-alt',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'people-carry',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'pepper-hot',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'phone-alt',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'pizza-slice',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'plane-arrival',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'plane-departure',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'place-of-worship',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'plug',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'poop',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'pray',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'prescription-bottle',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'puzzle-piece',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'rainbow',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'random',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'radiation',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'redo',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'ring',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'road',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'robot',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'rocket',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'ruler',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'running',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'screwdriver',
        tags: ['screwdriver'],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'seedling',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shape',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'share',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'shuttle-van',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'shower',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'skating',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'skiing',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'skull',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'smoking',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'snowman',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'FontAwesome5',
        iconName: 'spider',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'store-alt',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'syringe',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'sync-alt',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'table-tennis',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'tag',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'taxi',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'toilet',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'toolbox',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'tractor',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'truck-pickup',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'FontAwesome5',
        iconName: 'truck',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'trophy',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'FontAwesome5',
        iconName: 'tshirt',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'FontAwesome5',
        iconName: 'tv',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'FontAwesome5',
        iconName: 'umbrella-beach',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'unlock',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'FontAwesome5',
        iconName: 'user-friends',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'utensils',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'vial',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'walking',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'FontAwesome5',
        iconName: 'warehouse',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'FontAwesome5',
        iconName: 'wheelchair',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'wine-bottle',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'FontAwesome5',
        iconName: 'wine-glass',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'wrench',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'yin-yang',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'umbrella',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'magnet',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'FontAwesome5',
        iconName: 'flask',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'ban',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'FontAwesome5',
        iconName: 'power-off',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'map-outline',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'shopping-basket',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'star',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'medkit',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'FontAwesome5',
        iconName: 'yen-sign',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Ionicons',
        iconName: 'logo-bitcoin',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'Ionicons',
        iconName: 'barbell',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Ionicons',
        iconName: 'build',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Ionicons',
        iconName: 'bulb',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Ionicons',
        iconName: 'card',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'Ionicons',
        iconName: 'construct',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'cube',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'Ionicons',
        iconName: 'golf',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'Ionicons',
        iconName: 'hand-left',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'Ionicons',
        iconName: 'hand-right',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'Ionicons',
        iconName: 'home',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'Ionicons',
        iconName: 'ice-cream',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'layers',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'Ionicons',
        iconName: 'library-sharp',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'moon',
        tags: [],
    },
    {
        subcategory: 'time',
        iconFamily: 'Ionicons',
        iconName: 'notifications',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'Ionicons',
        iconName: 'newspaper',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'planet',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Ionicons',
        iconName: 'print',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'rainy',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'Ionicons',
        iconName: 'reader',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'Ionicons',
        iconName: 'school',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'shield',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'sunny',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'Ionicons',
        iconName: 'tennisball',
        tags: [],
    },
    {
        subcategory: 'time',
        iconFamily: 'Ionicons',
        iconName: 'time',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'Ionicons',
        iconName: 'trash-sharp',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'Ionicons',
        iconName: 'wallet-sharp',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'warning-sharp',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'Ionicons',
        iconName: 'water',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'Ionicons',
        iconName: 'ios-airplane',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'Ionicons',
        iconName: 'flag',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'Ionicons',
        iconName: 'calculator',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'alien',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'ambulance',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'arm-flex',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'axe',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'axe-battle',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'baguette',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'balloon',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bat',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'battery-high',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'billiards',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bird',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'blender',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bomb',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'FontAwesome5',
        iconName: 'book',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'bow-arrow',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'box-cutter',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'boxing-glove',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'broom',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'butterfly',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cactus',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'candy',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'card-text',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cards',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cat',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'dog',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'chat',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'checkerboard',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'chef-hat',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'comment-text',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'cow',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'earbuds',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'eraser',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'file',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'folder',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'food-apple',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'food-drumstick',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'french-fries',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'fridge',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'fruit-grapes',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'fruit-watermelon',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'hand-saw',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'hand-wave',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'human-male-female',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'jellyfish',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'karate',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'knife',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'knife-military',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'ladder',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'lamp',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mace',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'magic-staff',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mail',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mailbox',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'mirror',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'nuke',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'owl',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'panda',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'paper-roll-outline',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'party-popper',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'piano',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pickaxe',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pig-variant',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pliers',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pot-steam',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'pumpkin',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'rabbit',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'racing-helmet',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'rake',
        tags: [],
    },
    {
        subcategory: 'time',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'reminder',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'remote',
        tags: [],
    },
    {
        subcategory: 'food',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'rice',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'roller-skate',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sack',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sail-boat',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sd',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'seat',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'seed',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shoe-sneaker',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shoe-formal',
        tags: [],
    },
    {
        subcategory: 'clothing',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shoe-heel',
        tags: [],
    },
    {
        subcategory: 'commerce',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shopping',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shimmer',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'ship-wheel',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'shovel',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'skateboarding',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'snail',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'snake',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sofa',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'space-invaders',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'spray-bottle',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'sword',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'table-furniture',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'teddy-bear',
        tags: [],
    },
    {
        subcategory: 'fun',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'telescope',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'television-classic',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'terrain',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'tortoise',
        tags: [],
    },
    {
        subcategory: 'tech',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'usb-flash-drive',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'vacuum',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'virus',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'wall',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'yoga',
        tags: [],
    },
    {
        subcategory: 'symbols',
        iconFamily: 'MaterialIcons',
        iconName: '360',
        tags: [],
    },
    {
        subcategory: 'places',
        iconFamily: 'MaterialIcons',
        iconName: 'apartment',
        tags: [],
    },
    {
        subcategory: 'office',
        iconFamily: 'MaterialIcons',
        iconName: 'attachment',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialIcons',
        iconName: 'bathtub',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-boat',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-car',
        tags: [],
    },
    {
        subcategory: 'travel',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-bus',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-bike',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-walk',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'directions-run',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'elderly',
        tags: [],
    },
    {
        subcategory: 'people',
        iconFamily: 'MaterialIcons',
        iconName: 'fingerprint',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialIcons',
        iconName: 'local-fire-department',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'MaterialIcons',
        iconName: 'microwave',
        tags: [],
    },
    {
        subcategory: 'nature',
        iconFamily: 'MaterialIcons',
        iconName: 'pest-control-rodent',
        tags: [],
    },
    {
        subcategory: 'tools',
        iconFamily: 'MaterialIcons',
        iconName: 'plumbing',
        tags: [],
    },
    {
        subcategory: 'activity',
        iconFamily: 'MaterialIcons',
        iconName: 'pool',
        tags: [],
    },
    {
        subcategory: 'household',
        iconFamily: 'FontAwesome5',
        iconName: 'door-closed',
        tags: [],
    },
];
